image: gitpod/workspace-java-17

tasks:
  - init: "docker-compose up -d"

vscode:
    extensions:
      - vscjava.vscode-java-pack
      - humao.rest-client
      - vscjava.vscode-gradle

      - redhat.java

      - vscjava.vscode-java-debug

      - vscjava.vscode-java-dependency

      - vscjava.vscode-java-test

      - vscjava.vscode-maven

ports:
  - port: 8080
    visibility: public
